### ISSUE TITLE
login failed after 3 tries

### ISSUE THREAD

**Issue by Vip0r** [dstrigl/htheatpump#281]
* htheatpump version: 1.2.4
* Python version: 3
* Operating System: raspian 

### Description

Got a login failed error if i try to read/write any parameters. I already checked that "modem" is configured to "direkt/serial" in the heliotherm "fachman"-ebene. Below a traceback if i try for example to read the current datetime.

The helioterm software version i have is 3.0.40 (which is greater than any on the "tested"-list so far)

If i run another script in paralell to read the console output while executing the script i see also some "OK"-Strings in the response

Any idea what i can try to solve that?.

### What I Did

```
root@htcontrol:~# htdatetime -d /dev/ttyUSB0 -b 19200
HTHEATPUMP: load parameter definitions from: /usr/local/lib/python3.7/dist-packages/htheatpump/htparams.csv
2020-10-23 20:22:17,552 WARNING [htheatpump.htheatpump|login]: login try #1 failed: data stream broken during reading response header
2020-10-23 20:22:17,680 WARNING [htheatpump.htheatpump|login]: login try #2 failed: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
2020-10-23 20:22:22,813 WARNING [htheatpump.htheatpump|login]: login try #3 failed: data stream broken during reading payload
2020-10-23 20:22:22,915 ERROR [htheatpump.htheatpump|login]: login failed after 3 try/tries
2020-10-23 20:22:22,916 ERROR [htheatpump.scripts.htdatetime|main]: login failed after 3 try/tries
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/scripts/htdatetime.py", line 143, in main
    hp.login()
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/htheatpump.py", line 674, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/scripts/htdatetime.py", line 143, in main
    hp.login()
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/htheatpump.py", line 674, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/scripts/htdatetime.py", line 179, in main
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/htdatetime", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/scripts/htdatetime.py", line 181, in main
    hp.logout()  # try to logout for an ordinary cancellation (if possible)
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/htheatpump.py", line 687, in logout
    resp = self.read_response()
  File "/usr/local/lib/python3.7/dist-packages/htheatpump/htheatpump.py", line 589, in read_response
    payload = self._ser.read(payload_len)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
```

**Comment by Vip0r** [comment]
Strange...... i built the application from source and now it is working as expected... 👍
