### ISSUE TITLE
Frage zu Fehlermeldung : data stream broken during reading response header

### ISSUE THREAD

**Issue by FosslKL** [dstrigl/htheatpump#388]
Hallo Daniel 
Ich darf mich kurz vorstellen.
Ich heiße Hannes, wohne in Klagenfurt und bin in das Thema „Smarthome“ voll reingekippt.

Erstmals muss ich mich bei die bedanken, dass es solche Enthusiasten wie dich gibt und
das ihr eure Projekte uns über Github kostenlos zur Verfügung stellt.

Ich betreibe einen Raspberry mit Openhab und möchte meine Wärmepumpe gerne ins Openhab einbinden. Ich besitze eine „Heliotherm HP08E-WEB“ Baujahr 2006.

Ich bin beim Googlen auf deine Projekte htheatpump und htrest gestoßen.
Die zwei Programme wurden wie von dir beschrieben fehlerlos installiert, der Raspberry ist über einen Serial2Usb Adapter und einen Nullmodemkabel mit X26 der WP verbunden.

Ich hätte nur eine Frage. Wird diese WP Type von deinen Programmen auch unterstützt,
oder kann das gar nicht funktionieren?

Ich bekomme nämlich eine Fehlermeldung beim connecten zur WP.
Details Befehl htquery:

root@raspberrypi:/home/pi# ls -l /dev/serial/by-id
lrwxrwxrwx 1 root root 13 Mar 15 22:01 usb-ftdi_usb_serial_converter_ftDW2VUL-if00-port0 -> ../../ttyUSB0
root@raspberrypi:/home/pi# htquery --device /dev/ttyUSB0 "Temp. Aussen"
2022-03-15 22:47:15,739 WARNING [htheatpump.htheatpump|login]: login try #1 failed: data stream broken during reading response header
2022-03-15 22:47:20,855 WARNING [htheatpump.htheatpump|login]: login try #2 failed: data stream broken during reading response header
2022-03-15 22:47:25,971 WARNING [htheatpump.htheatpump|login]: login try #3 failed: data stream broken during reading response header
2022-03-15 22:47:26,083 ERROR [htheatpump.htheatpump|login]: login failed after 3 try/tries
2022-03-15 22:47:26,083 ERROR [htheatpump.scripts.htquery|main]: login failed after 3 try/tries
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/scripts/htquery.py", line 140, in main
    hp.login()
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htheatpump.py", line 504, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries
2022-03-15 22:47:31,094 WARNING [htheatpump.htheatpump|logout]: logout failed: data stream broken during reading response header
root@raspberrypi:/home/pi#

Details: htrest Installation

pi@raspberrypi:~ $ sudo -s
root@raspberrypi:/home/pi# pip install HtREST --upgrade
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting HtREST
  Downloading https://www.piwheels.org/simple/htrest/htrest-0.1.11-py3-none-any.whl (35 kB)
Collecting Flask==2.0.3
  Downloading https://www.piwheels.org/simple/flask/Flask-2.0.3-py3-none-any.whl (95 kB)
     |████████████████████████████████| 95 kB 526 kB/s
Collecting flask-restx==0.5.1
  Downloading https://www.piwheels.org/simple/flask-restx/flask_restx-0.5.1-py2.py3-none-any.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 1.3 MB/s
Collecting Flask-BasicAuth==0.2.0
  Downloading https://www.piwheels.org/simple/flask-basicauth/Flask_BasicAuth-0.2.0-py3-none-any.whl (4.8 kB)
Requirement already satisfied: htheatpump==1.3.2 in /usr/local/lib/python3.9/dist-packages (from HtREST) (1.3.2)
Collecting Werkzeug>=2.0
  Downloading https://www.piwheels.org/simple/werkzeug/Werkzeug-2.0.3-py3-none-any.whl (289 kB)
     |████████████████████████████████| 289 kB 654 kB/s
Collecting Jinja2>=3.0
  Downloading https://www.piwheels.org/simple/jinja2/Jinja2-3.0.3-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 880 kB/s
Collecting itsdangerous>=2.0
  Downloading https://www.piwheels.org/simple/itsdangerous/itsdangerous-2.1.1-py3-none-any.whl (15 kB)
Collecting click>=7.1.2
  Downloading https://www.piwheels.org/simple/click/click-8.0.4-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 864 kB/s
Collecting jsonschema
  Downloading https://www.piwheels.org/simple/jsonschema/jsonschema-4.4.0-py3-none-any.whl (72 kB)
     |████████████████████████████████| 72 kB 293 kB/s
Collecting aniso8601>=0.82
  Downloading https://www.piwheels.org/simple/aniso8601/aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 328 kB/s
Requirement already satisfied: six>=1.3.0 in /usr/lib/python3/dist-packages (from flask-restx==0.5.1->HtREST) (1.16.0)
Collecting pytz
  Downloading https://www.piwheels.org/simple/pytz/pytz-2021.3-py3-none-any.whl (511 kB)
     |████████████████████████████████| 511 kB 695 kB/s
Requirement already satisfied: aioserial==1.3.0 in /usr/local/lib/python3.9/dist-packages (from htheatpump==1.3.2->HtREST) (1.3.0)
Requirement already satisfied: pyserial==3.5 in /usr/local/lib/python3.9/dist-packages (from htheatpump==1.3.2->HtREST) (3.5)
Collecting MarkupSafe>=2.0
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-2.1.1-cp39-cp39-linux_armv7l.whl (23 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading https://www.piwheels.org/simple/pyrsistent/pyrsistent-0.18.1-cp39-cp39-linux_armv7l.whl (101 kB)
     |████████████████████████████████| 101 kB 551 kB/s
Collecting attrs>=17.4.0
  Downloading https://www.piwheels.org/simple/attrs/attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 916 kB/s
Installing collected packages: MarkupSafe, Werkzeug, pyrsistent, Jinja2, itsdangerous, click, attrs, pytz, jsonschema, Flask, aniso8601, flask-restx, Flask-BasicAuth, HtREST
Successfully installed Flask-2.0.3 Flask-BasicAuth-0.2.0 HtREST-0.1.11 Jinja2-3.0.3 MarkupSafe-2.1.1 Werkzeug-2.0.3 aniso8601-9.0.1 attrs-21.4.0 click-8.0.4 flask-restx-0.5.1 itsdangerous-2.1.1 jsonschema-4.4.0 pyrsistent-0.18.1 pytz-2021.3
root@raspberrypi:/home/pi#
Befehl : htrest -d /dev/ttyUSB0 -b 115200 --host 10.0.0.66 --port 8777 --read-only
root@raspberrypi:/home/pi# htrest -d /dev/ttyUSB0 -b 115200 --host 10.0.0.66 --port 8777 --read-only
Start Heliotherm heat pump REST API server v0.1.11.
Namespace(device='/dev/ttyUSB0', baudrate=115200, host='10.0.0.66', port=8777, user='', bool_as_int=False, logging_config='/usr/local/lib/python3.9/dist-packages/htrest/logging.conf', debug=False, read_only=True, no_param_verification=False)
2022-03-15 23:15:37,453 INFO [htrest.app|create_app]: open connection to heat pump (<htheatpump.htheatpump.HtHeatpump object at 0xb5cd7a18>)
2022-03-15 23:15:42,465 WARNING [htheatpump.htheatpump|login]: login try #1 failed: data stream broken during reading response header
2022-03-15 23:15:47,582 WARNING [htheatpump.htheatpump|login]: login try #2 failed: data stream broken during reading response header
2022-03-15 23:15:52,698 WARNING [htheatpump.htheatpump|login]: login try #3 failed: data stream broken during reading response header
2022-03-15 23:15:52,809 ERROR [htheatpump.htheatpump|login]: login failed after 3 try/tries
2022-03-15 23:15:52,810 ERROR [htrest.app|create_app]: login failed after 3 try/tries
2022-03-15 23:15:57,816 WARNING [htheatpump.htheatpump|logout]: logout failed: data stream broken during reading response header
Traceback (most recent call last):
  File "/usr/local/bin/htrest", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/htrest/__main__.py", line 183, in main
    app = create_app(
  File "/usr/local/lib/python3.9/dist-packages/htrest/app.py", line 51, in create_app
    ht_heatpump.login()
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htheatpump.py", line 504, in login
    raise IOError("login failed after {:d} try/tries".format(retry))
OSError: login failed after 3 try/tries
root@raspberrypi:/home/pi#

Wäre echt super wenn du mir kurz Bescheid geben könnest ob es generell nicht geht, oder ob ich vielleicht ein Problem mit dem Adapter, Kabel etc…. habe.
Lg aus Kärnten Hannes

**Comment by dstrigl** [comment]
Hallo Hannes,

vielen lieben Dank für deine Nachricht und die "Blumen" :-)

> Ich hätte nur eine Frage. Wird diese WP Type von deinen Programmen auch unterstützt,
> oder kann das gar nicht funktionieren?

Sollte meines Erachtens funktionieren, auch wenn die WP doch schon etwas älter ist.
Eventuell kennt sie noch nicht alle Datenpunkte der neueren Modelle, aber das sollte für dich nicht relevant sein ...
Glaube nicht, dass Heliotherm am Protokoll von deinem Modell zu den anderen großartig was geändert hat.
Das Protokoll ist doch etwas "altbacken", aber es funktioniert ;-)

> Ich bekomme nämlich eine Fehlermeldung beim connecten zur WP.
> Details Befehl htquery:
> ...

Prüfe hierzu bitte zuerst einmal die Einstellungen der seriellen Schnittstelle.
Diese müssen sowohl an der WP, als auch auf deinem RPi zusammenpassen!
Eventuell kann man an deiner WP (da etwas älteres Modell) noch keine Einstellungen der seriellen Schnittstelle vornehmen,
da diese mit fixen Einstellungen (z.B. fixer Baudrate) läuft.
Da müsstest du dann etwas herumprobieren ...
Siehe dazu auch unter
https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source
den Punkt "Installation & Test" und dort unter
"Zu beachten ist auch, dass die verwendete Baudrate der seriellen Verbindung mit der Einstellung auf der Wärmepumpe übereinstimmen muss."
die nachfolgende Beschreibung.

LG Daniel.

**Comment by FosslKL** [comment]
Hallo Daniel
Danke für deine schnelle Antwort 😊 und für die zur Verfügung gestellten Links , ich werde die Einstellungen heute am Abend überprüfen und gebe dir dann auf alles Fälle Bescheid.

Lg aus Kärnten 
Hannes

**Comment by FosslKL** [comment]
Hallo Daniel 

Dein Tipp war goldrichtig, anscheinend habe ich die ältere Version die nur fix 19200 Baud kann.
Ich kommuniziere mit beiden Projekten ( htheatpump + htrest ) und bin begeistert.

Einige Einschränkung ist :
Wenn ich die Option  „/api/v1/param“ verwende kommt es zu einer Fehlermeldung, aber ich vermute das da der ältere Software Stand das Problem verursacht. 

Detail : 

pi@raspberrypi:~ $ curl -X GET "http://localhost:8777/api/v1/param/" -H "accept: application/json"

2022-03-16 16:25:32,730 INFO [htrest.apis.param|get]: *** [GET] http://localhost:8777/api/v1/param/
2022-03-16 16:25:33,170 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'Temp. Aussen verzoegert' failed: (VerificationException(...), "parameter name doesn't match with 'Temp. Aussen verzoegert' ['Temp. Aussen verzoeg']")
2022-03-16 16:25:34,530 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'Temp. Frischwasser_Istwert' failed: (VerificationException(...), "parameter name doesn't match with 'Temp. Frischwasser_Istwert' ['Temp. Frischwasser_I']")
2022-03-16 16:25:35,889 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'EQ Pumpe (Ventilator)' failed: (VerificationException(...), "parameter name doesn't match with 'EQ Pumpe (Ventilator)' ['EQ Pumpe (Ventilator']")
2022-03-16 16:25:36,977 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'FWS Stroemungsschalter' failed: (VerificationException(...), "parameter name doesn't match with 'FWS Stroemungsschalter' ['FWS Stroemungsschalt']")
2022-03-16 16:25:37,153 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'BSZ Verdichter Schaltungen' failed: (VerificationException(...), "parameter name doesn't match with 'BSZ Verdichter Schaltungen' ['Z Impulse Stromzaehl']")
2022-03-16 16:25:37,473 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'Verdichteranforderung' failed: (VerificationException(...), "parameter name doesn't match with 'Verdichteranforderung' ['Verdichteranforderun']")
2022-03-16 16:25:38,369 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'Verdichter laeuft seit' failed: (VerificationException(...), "parameter name doesn't match with 'Verdichter laeuft seit' ['Verdichter laeuft se']")
2022-03-16 16:25:38,481 WARNING [htheatpump.htheatpump|_verify_param_resp]: response verification of param 'Verdichter Einschaltverz.(sec)' failed: (VerificationException(...), "parameter name doesn't match with 'Verdichter Einschaltverz.(sec)' ['Verdichter Einschalt']")
2022-03-16 16:25:38,689 ERROR [htheatpump.htheatpump|_get_param]: query of parameter 'HKR Soll_Raum' failed: invalid representation for data type FLOAT ('10')
2022-03-16 16:25:38,689 ERROR [htheatpump.htheatpump|get_param]: get parameter 'HKR Soll_Raum' failed: invalid representation for data type FLOAT ('10')
2022-03-16 16:25:38,722 ERROR [htrest.apiv1|default_error_handler]: *** @api.errorhandler -- invalid representation for data type FLOAT ('10')
2022-03-16 16:25:38,722 ERROR [htrest.app|log_exception]: Exception on /api/v1/param/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_restx/marshalling.py", line 248, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/htrest/apis/param.py", line 63, in get
    value = ht_heatpump.get_param(name)
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htheatpump.py", line 1085, in get_param
    resp = self._get_param(name)
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htheatpump.py", line 933, in _get_param
    return self._extract_param_data(name, resp)
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htheatpump.py", line 893, in _extract_param_data
    resp_min = param.from_str(
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htparams.py", line 274, in from_str
    return HtParam._from_str(arg, self.data_type, strict)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/htheatpump/htparams.py", line 235, in _from_str
    raise ValueError(
ValueError: invalid representation for data type FLOAT ('10')


Einzelwerte oder fastquery ist kein Problem.

pi@raspberrypi:~ $ curl -X GET "http://localhost:8777/api/v1/param/Temp.%20Aussen" -H "accept: application/json"
{"value": 13.1}
pi@raspberrypi:~ $

funnktioniert:
pi@raspberrypi:~ $ curl -X GET "http://localhost:8777/api/v1/fastquery/" -H "accept: application/json"
{"HKR_Sollwert": 27.2, "Verdichteranforderung": 0, "Frischwasserpumpe": 0, "BSZ Verdichter Schaltungen": 1, "FWS Stroemungsschalter": false, "Hauptschalter": true, "Stoerung": false, "Verdichter": false, "Zirkulationspumpe WW": false, "Warmwasservorrang": false, "EQ Pumpe (Ventilator)": false, "Heizkreispumpe": false, "Hochdruck (bar)": 14.7, "Niederdruck (bar)": 8.0, "Temp. Heissgas": 23.4, "Temp. Kondensation": 22.8, "Temp. Verdampfung": 3.4, "Temp. Frischwasser_Istwert": 40.9, "Temp. Sauggas": -50.0, "Temp. EQ_Austritt": -50.0, "Temp. EQ_Eintritt": -50.0, "Temp. Ruecklauf": 23.0, "Temp. Vorlauf": 23.9, "Temp. Brauchwasser": 44.4, "Temp. Aussen verzoegert": 13.8, "Temp. Aussen": 13.1}
pi@raspberrypi:~ $


Daniel, deine Projekte machen mir sehr viel Freude, endlich kann ich die WP im Openhab integrieren.

Hast du PayPal  ? 

Bitte teile mir deine Adresse mit damit ich dir eine Kiste Bier überweisen kann.
Ich würde dass gerne machen weil es mir so taugt :-)

lg Hannes
